/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CredentialVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getCredential"
      | "getOwnerCredentials"
      | "isVerifierAuthorized"
      | "registerCredential"
      | "revokeCredential"
      | "setVerifierAuthorization"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialQueried"
      | "CredentialRegistered"
      | "CredentialRevoked"
      | "VerifierAuthorizationUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getCredential",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerCredentials",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifierAuthorized",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCredential",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifierAuthorization",
    values: [BigNumberish, AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVerifierAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifierAuthorization",
    data: BytesLike
  ): Result;
}

export namespace CredentialQueriedEvent {
  export type InputTuple = [
    id: BigNumberish,
    querier: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [id: bigint, querier: string, timestamp: bigint];
  export interface OutputObject {
    id: bigint;
    querier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRegisteredEvent {
  export type InputTuple = [
    id: BigNumberish,
    owner: AddressLike,
    docHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    owner: string,
    docHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    owner: string;
    docHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [id: BigNumberish, owner: AddressLike];
  export type OutputTuple = [id: bigint, owner: string];
  export interface OutputObject {
    id: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierAuthorizationUpdatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    owner: AddressLike,
    verifier: AddressLike,
    authorized: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    owner: string,
    verifier: string,
    authorized: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    owner: string;
    verifier: string;
    authorized: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CredentialVault extends BaseContract {
  connect(runner?: ContractRunner | null): CredentialVault;
  waitForDeployment(): Promise<this>;

  interface: CredentialVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCredential: TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, string, string, string, bigint, boolean] & {
        credentialId: bigint;
        owner: string;
        docHash: string;
        encryptedPayload: string;
        createdAt: bigint;
        revoked: boolean;
      }
    ],
    "nonpayable"
  >;

  getOwnerCredentials: TypedContractMethod<
    [owner: AddressLike],
    [bigint[]],
    "view"
  >;

  isVerifierAuthorized: TypedContractMethod<
    [id: BigNumberish, verifier: AddressLike],
    [boolean],
    "view"
  >;

  registerCredential: TypedContractMethod<
    [docHash: BytesLike, encryptedPayload: string],
    [bigint],
    "nonpayable"
  >;

  revokeCredential: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVerifierAuthorization: TypedContractMethod<
    [id: BigNumberish, verifier: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCredential"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, string, string, string, bigint, boolean] & {
        credentialId: bigint;
        owner: string;
        docHash: string;
        encryptedPayload: string;
        createdAt: bigint;
        revoked: boolean;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOwnerCredentials"
  ): TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isVerifierAuthorized"
  ): TypedContractMethod<
    [id: BigNumberish, verifier: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerCredential"
  ): TypedContractMethod<
    [docHash: BytesLike, encryptedPayload: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerifierAuthorization"
  ): TypedContractMethod<
    [id: BigNumberish, verifier: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CredentialQueried"
  ): TypedContractEvent<
    CredentialQueriedEvent.InputTuple,
    CredentialQueriedEvent.OutputTuple,
    CredentialQueriedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRegistered"
  ): TypedContractEvent<
    CredentialRegisteredEvent.InputTuple,
    CredentialRegisteredEvent.OutputTuple,
    CredentialRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierAuthorizationUpdated"
  ): TypedContractEvent<
    VerifierAuthorizationUpdatedEvent.InputTuple,
    VerifierAuthorizationUpdatedEvent.OutputTuple,
    VerifierAuthorizationUpdatedEvent.OutputObject
  >;

  filters: {
    "CredentialQueried(uint256,address,uint64)": TypedContractEvent<
      CredentialQueriedEvent.InputTuple,
      CredentialQueriedEvent.OutputTuple,
      CredentialQueriedEvent.OutputObject
    >;
    CredentialQueried: TypedContractEvent<
      CredentialQueriedEvent.InputTuple,
      CredentialQueriedEvent.OutputTuple,
      CredentialQueriedEvent.OutputObject
    >;

    "CredentialRegistered(uint256,address,bytes32,uint64)": TypedContractEvent<
      CredentialRegisteredEvent.InputTuple,
      CredentialRegisteredEvent.OutputTuple,
      CredentialRegisteredEvent.OutputObject
    >;
    CredentialRegistered: TypedContractEvent<
      CredentialRegisteredEvent.InputTuple,
      CredentialRegisteredEvent.OutputTuple,
      CredentialRegisteredEvent.OutputObject
    >;

    "CredentialRevoked(uint256,address)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "VerifierAuthorizationUpdated(uint256,address,address,bool,uint64)": TypedContractEvent<
      VerifierAuthorizationUpdatedEvent.InputTuple,
      VerifierAuthorizationUpdatedEvent.OutputTuple,
      VerifierAuthorizationUpdatedEvent.OutputObject
    >;
    VerifierAuthorizationUpdated: TypedContractEvent<
      VerifierAuthorizationUpdatedEvent.InputTuple,
      VerifierAuthorizationUpdatedEvent.OutputTuple,
      VerifierAuthorizationUpdatedEvent.OutputObject
    >;
  };
}
