/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WorldSimulationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applyEncryptedDecision"
      | "getDecisionsCount"
      | "getWorldState"
      | "protocolId"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DecisionApplied"): EventFragment;

  encodeFunctionData(
    functionFragment: "applyEncryptedDecision",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecisionsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWorldState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "applyEncryptedDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecisionsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorldState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export namespace DecisionAppliedEvent {
  export type InputTuple = [sender: AddressLike];
  export type OutputTuple = [sender: string];
  export interface OutputObject {
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorldSimulation extends BaseContract {
  connect(runner?: ContractRunner | null): WorldSimulation;
  waitForDeployment(): Promise<this>;

  interface: WorldSimulationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applyEncryptedDecision: TypedContractMethod<
    [
      worldEvolutionDeltaHandle: BytesLike,
      stabilityDeltaHandle: BytesLike,
      innovationDeltaHandle: BytesLike,
      mysteryDeltaHandle: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getDecisionsCount: TypedContractMethod<[], [string], "view">;

  getWorldState: TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        worldEvolution: string;
        stability: string;
        innovation: string;
        mystery: string;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applyEncryptedDecision"
  ): TypedContractMethod<
    [
      worldEvolutionDeltaHandle: BytesLike,
      stabilityDeltaHandle: BytesLike,
      innovationDeltaHandle: BytesLike,
      mysteryDeltaHandle: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDecisionsCount"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getWorldState"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        worldEvolution: string;
        stability: string;
        innovation: string;
        mystery: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DecisionApplied"
  ): TypedContractEvent<
    DecisionAppliedEvent.InputTuple,
    DecisionAppliedEvent.OutputTuple,
    DecisionAppliedEvent.OutputObject
  >;

  filters: {
    "DecisionApplied(address)": TypedContractEvent<
      DecisionAppliedEvent.InputTuple,
      DecisionAppliedEvent.OutputTuple,
      DecisionAppliedEvent.OutputObject
    >;
    DecisionApplied: TypedContractEvent<
      DecisionAppliedEvent.InputTuple,
      DecisionAppliedEvent.OutputTuple,
      DecisionAppliedEvent.OutputObject
    >;
  };
}
